---

- hosts: 10.0.0.240
  become: true
  tasks:
  
  - name: update repository index
    yum:
      update_cache: yes

  - name: install apache2 package
    yum:
      name: httpd
      state: latest


